# Generated by Django 5.2 on 2025-04-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouch_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.CharField(null=True),
        ),
    ]
